name: PR Checking

on:
  pull_request:
    paths:
    - 'build/centos-stream-8/**'

jobs:
  build-packages-for-centos-stream-8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Build shim package
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-guest-shim
