name: PR General Checking

on: [pull_request]

jobs:
  codescan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
